### ISSUE TITLE
example on how to create/write a genbank record?

### ISSUE THREAD

**Issue by nextgenusfs** [althonos/gb-io.py#38]
@althonos can this also create/write a new genbank record? Lets say I have FASTA and gene/cds annotation in a dictionary, how would I write this to a genbank formatted record? Trying to avoid biopython for a project. Thanks!

**Comment by BjornFJohansson** [comment]
You can use Biopython or Pydna for that. I think this library only parse and do not write.

**Comment by nextgenusfs** [comment]
Was hoping to drop biopython as dependency, as this is much much faster. There is an .dump() function to write, was just looking to see how to create the records object from scratch when not starting with a genbank file.

**Comment by BjornFJohansson** [comment]
That's an interesting addon. Will you be implementing that?

**Comment by althonos** [comment]
That's something I want to add eventually, but for that I'd need to change how the records are handled internally to use reference-counting so that it follows Python semantics.
At the moment the `dump` function is to write the records so that you could use the library to filter another file, but there is no way to create records from scratch, I'll see when I have time :+1:

**Comment by althonos** [comment]
Hi, just to let you know I'm working on this now and it should be working in the next minor release (`v0.3.0`).

**Comment by althonos** [comment]
You can now create records from Python code, see the API reference at https://gb-io.readthedocs.io/en/stable/api/index.html for the constructor arguments. Once the record have been created, they can be written to a file or file-like handle using the `gb_io.dump` function.
